// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExpandImageController from "./expand_image_controller"
application.register("expand-image", ExpandImageController)

import PwaInstallController from "./pwa_install_controller"
application.register("pwa-install", PwaInstallController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import VisualizationCategorySwitchController from "./visualization_category_switch_controller"
application.register("visualization-category-switch", VisualizationCategorySwitchController)
